### ISSUE TITLE
Members Subscription

### ISSUE THREAD

**Issue by bueltge** [inpsyde/Inform-about-Content#12]
Is there a possibility of adding Members Notification as well?
So everyone knows when a new member joins?

see: http://wordpress.org/support/topic/members-subscription?replies=3

**Comment by dnaber-de** [comment]
It's possible however, we will have to define the use cases: All subscribers in one site (3. Option »Inform about new users«) gets an email, when a new user is registered to this site?

**Comment by bueltge** [comment]
And after this mail, the user must confirm the subscription?

**Comment by dnaber-de** [comment]
For what reason?

**Comment by dnaber-de** [comment]
@bueltge ?

**Comment by bueltge** [comment]
We should close this, long time ago, to long for a valid discussion.
