### ISSUE TITLE
Semver

### ISSUE THREAD

**Issue by dnaber-de** [inpsyde/Inform-about-Content#15]
This. Just increasing a arbitrary figure in a line of three doesn't say anything about the changes that were made. 

Next release will be `1.0.0` no mater what has changed and from then we follow the principle of [semver](http://semver.org).

**Comment by dnaber-de** [comment]
Just tagged the last commit with `1.0.0-beta1`. 1.0.0 is almost here.

**Comment by bueltge** [comment]
+1
