### ISSUE TITLE
Add composer support

### ISSUE THREAD

**Issue by dnaber-de** [inpsyde/Inform-about-Content#17]
Package name: `inpsyde/informer`.

**Comment by bueltge** [comment]
I miss the packagist entry? https://packagist.org/users/inpsyde/

**Comment by bueltge** [comment]
Done. 
https://packagist.org/packages/inpsyde/informer

**Comment by dnaber-de** [comment]
@bueltge @nullbytes Thanks but you could also let me complete my job ;)

**Comment by bueltge** [comment]
Oh, was not clear for me, that you can create Inpsyde entries on packagist

**Comment by dnaber-de** [comment]
You can submit any package you want.

**Comment by bueltge** [comment]
But in the namespace of Inpsyde, was for other examples not possible for me. That's was my point that I involved Robert.
